name: Feature Request
description: Suggest an improvement or new feature.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion!

        Please keep requests focused and describe the use-case. "Why" matters as much as "what".

  - type: input
    id: addon
    attributes:
      label: Addon Name
      description: Which addon is this for?
      placeholder: e.g. Mythic Dungeon Teleports
    validations:
      required: true

  - type: textarea
    id: request
    attributes:
      label: What would you like to see added or improved?
      placeholder: e.g. Add a toggle to hide unlearned teleports completely.
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why is this useful?
      description: The use-case, not just the idea.
      placeholder: e.g. I only want to see teleports I can actually use, to reduce clutter.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered (optional)
      placeholder: e.g. A filter dropdown: All / Known Only / Unknown Only.
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Extra notes / screenshots
    validations:
      required: false
